image: node:4.2.2

stages:
  - deploy

pages:
  stage: deploy
  script:
    - ./script/cibuild-pre
    - npm run build 
    - ./script/build
  artifacts:
    paths:
      - public
  only: 
    - master
