#!/bin/bash

function writeCHECK {
  touch ./public/CHECK.json \
    && echo "{ \"timestamp\": \"$(date)\" }" >> ./public/CHECK.json;
}

### SET DEPLOY URL ###
DEPLOY_URL="";
if [ "$STAGE" == "STAGING" ]; then
  DEPLOY_URL="http://staging.chaseadams.io";
elif [ "$STAGE" == "PRODUCTION" ]; then
  DEPLOY_URL="http://chaseadams.io";
fi


hugo --baseURL=${DEPLOY_URL} \
  && writeCHECK

