#!/bin/bash

function writeStatus {
  touch ./public/status.json \
    && echo "{ \"status\": \"good\", \"last_build\": \"$(($(date +%s)*1000))\" }" >> ./public/status.json;
}

# build the theme on the fly
npm run build

HUGO_BASEURL="https://chaseadams.io" hugo \
  && writeStatus

