#!/bin/bash

function writeStatus {
  touch ./public/status.json \
    && echo "{ \"status\": \"good\", \"last_build\": \"$(($(date +%s)*1000))\" }" >> ./public/status.json;
}

# build the theme on the fly
cd themes/minimalist && npm run build && cd ../../

HUGO_BASEURL="https://chaseadams.io" ./bin/hugo_linux_386 \
  && writeStatus

